services:
  onlyoffice-documentserver:
    build:
      context: .
      args:
        - PACKAGE_IDENTIFIER=${PACKAGE_IDENTIFIER}
        - PACKAGE_VERSION=${PACKAGE_VERSION}
        - PACKAGE_BASEURL=${PACKAGE_BASEURL}
      target: documentserver-community
    image: naiss/onlyoffice
    container_name: onlyoffice-documentserver
    environment:
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
      - LETS_ENCRYPT_DOMAIN=${LETS_ENCRYPT_DOMAIN}
      - LETS_ENCRYPT_MAIL=${LETS_ENCRYPT_MAIL}
      - TZ=${TZ}
    ports:
      - '80:80'
      - '443:443'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
        - /app/onlyoffice/letsencrypt:/etc/letsencrypt
        - /app/onlyoffice/logs:/var/log/onlyoffice
        - /app/onlyoffice/data:/var/www/onlyoffice/Data
        - /app/onlyoffice/lib:/var/lib/onlyoffice
        - /app/onlyoffice/fonts:/usr/share/fonts
        - type: bind
          source: ./local-production-linux.json
          target: /etc/onlyoffice/documentserver/local-production-linux.json
